#!/usr/bin/env python3
"""Merge per-system VectorDBBench-style reports into one comparison.

Reads the `logpose-vdb-report/1` reports written by `logpose-bench vdb-run` and
`scripts/bench/milvus_vdb.py` for one dataset and writes:

- a JSON document holding both reports unchanged plus run resources, and
- a Markdown summary with one table per case at the ef each system needed to
  reach the target recall.

Only the Python standard library is needed.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

COMPARISON_SCHEMA = "logpose-vdb-comparison/1"
SYSTEM_LABELS = {"logpose": "LogPose", "milvus": "Milvus"}


def fmt(value: float | None, digits: int = 1) -> str:
    if value is None:
        return "n/a"
    return f"{value:,.{digits}f}"


def gib(value: str | int | None) -> str:
    try:
        return f"{int(value) / (1 << 30):.2f} GiB"
    except (TypeError, ValueError):
        return str(value) if value else "n/a"


def load_report(path: str) -> dict:
    report = json.loads(Path(path).read_text())
    if report.get("schema") != "logpose-vdb-report/1":
        raise ValueError(f"{path} is not a logpose-vdb-report/1 report")
    return report


def check_same_dataset(reports: dict[str, dict]) -> dict:
    manifests = {name: report["dataset"] for name, report in reports.items()}
    first_name, first = next(iter(manifests.items()))
    for name, manifest in manifests.items():
        for key in ("name", "generator", "n", "dims", "queries", "k", "cases"):
            if manifest.get(key) != first.get(key):
                raise ValueError(f"{name} and {first_name} ran different datasets ({key} differs)")
    return first


def by_clients(case: dict) -> dict[int, dict]:
    return {run["clients"]: run for run in case.get("concurrency", [])}


def markdown(comparison: dict) -> str:
    systems = comparison["systems"]
    dataset = comparison["dataset"]
    generator = dataset["generator"]
    machine = comparison["machine"]
    resources = comparison["resources"]
    target = comparison["target_recall"]
    names = [name for name in ("logpose", "milvus") if name in systems]
    clients = sorted({c for report in systems.values() for case in report["cases"] for c in by_clients(case)})
    lines: list[str] = []
    add = lines.append

    add(f"# Phase 5 Milvus Comparison: {dataset['name']}")
    add("")
    add("Generated by `scripts/bench-milvus.sh`; do not edit by hand. See `benches/baselines/README.md` for how to read it.")
    add("")
    if dataset.get("synthetic"):
        add(
            f"**Synthetic data.** {dataset['n']:,} vectors of {dataset['dims']} dimensions and {dataset['queries']:,} queries, "
            f"{dataset['metric']} metric, from the embedding-like generator ({generator['latent_dims']} latent dimensions, "
            f"{generator['clusters']} clusters, seed {generator['seed']}). It mirrors only the shape of "
            f"{dataset.get('mirrors') or 'no public dataset'}; the public VectorDBBench files were not reachable."
        )
    else:
        add(f"{dataset['n']:,} vectors of {dataset['dims']} dimensions, {dataset['queries']:,} queries, {dataset['metric']} metric.")
    add("")
    add(f"Recall is mean recall@{dataset['k']} against exact ground truth. Each system's `ef` is the smallest swept value with recall of at least {target}.")
    add("")

    add("## Setup")
    add("")
    add("| Item | Value |")
    add("| --- | --- |")
    add(f"| Run date (UTC) | {comparison['generated_at']} |")
    add(f"| CPU | {machine.get('cpu_model') or 'n/a'}, {machine.get('logical_cpus')} logical CPUs |")
    add(f"| Memory | {gib(machine.get('total_memory_bytes'))} |")
    add(f"| Kernel | {machine.get('kernel') or 'n/a'} |")
    add(f"| LogPose commit | `{(machine.get('git_commit') or 'n/a')[:12]}`{' (dirty tree)' if machine.get('git_dirty') else ''} |")
    for name in names:
        report = systems[name]
        index = report["index"]
        add(
            f"| {SYSTEM_LABELS[name]} | {report.get('system_version') or 'n/a'}; HNSW M={index['m']}, "
            f"efConstruction={index['ef_construction']}; {index.get('quantization', '')}; scalar index {index.get('scalar_index', 'n/a')} |"
        )
    for key, value in resources.items():
        add(f"| {key.replace('_', ' ')} | {gib(value) if key.endswith('_bytes') else value} |")
    add("")

    add("## Load")
    add("")
    add("| System | Rows | Insert s | Optimize s | Total s | Insert rows/s |")
    add("| --- | --- | --- | --- | --- | --- |")
    for name in names:
        load = systems[name]["load"]
        add(
            f"| {SYSTEM_LABELS[name]} | {load['rows']:,} | {fmt(load['insert_seconds'])} | {fmt(load['optimize_seconds'])} | "
            f"{fmt(load['total_seconds'])} | {fmt(load['insert_rows_per_sec'], 0)} |"
        )
    add("")
    add("Optimize is everything after the last insert until the data is fully indexed and searchable: flush, compaction, and index build (and for Milvus, reloading the collection).")
    add("")

    add("## Search")
    add("")
    case_names = [case["name"] for case in systems[names[0]]["cases"]]
    for case_name in case_names:
        first = next(case for case in systems[names[0]]["cases"] if case["name"] == case_name)
        title = case_name if not first.get("filter") else f"{case_name} (`{first['filter']}`, {first['matching_rows']:,} rows)"
        add(f"### {title}")
        add("")
        header = ["System", "ef", "Recall"]
        header += [f"QPS {c}c" for c in clients]
        header += ["p50 ms 1c", "p99 ms 1c"]
        if clients and clients[-1] != 1:
            header += [f"p99 ms {clients[-1]}c"]
        add("| " + " | ".join(header) + " |")
        add("|" + " --- |" * len(header))
        for name in names:
            case = next((c for c in systems[name]["cases"] if c["name"] == case_name), None)
            if case is None:
                continue
            runs = by_clients(case)
            chosen = next((p for p in case["sweep"] if p["ef"] == case["chosen_ef"]), None)
            recall = f"{case['chosen_recall']:.4f}" + ("" if case["met_target"] else " (below target)")
            row = [SYSTEM_LABELS[name], str(case["chosen_ef"]), recall]
            row += [fmt(runs[c]["qps"]) if c in runs else "n/a" for c in clients]
            single = runs.get(1)
            p50 = single["latency"]["p50_ms"] if single else (chosen["latency"]["p50_ms"] if chosen else None)
            p99 = single["latency"]["p99_ms"] if single else (chosen["latency"]["p99_ms"] if chosen else None)
            row += [fmt(p50, 2), fmt(p99, 2)]
            if clients and clients[-1] != 1:
                last = runs.get(clients[-1])
                row += [fmt(last["latency"]["p99_ms"], 2) if last else "n/a"]
            add("| " + " | ".join(row) + " |")
        add("")
        for name in names:
            case = next((c for c in systems[name]["cases"] if c["name"] == case_name), None)
            if case is None:
                continue
            sweep = ", ".join(f"ef {p['ef']}: {p['recall']:.3f}" for p in case["sweep"])
            plan = ""
            if case.get("plan"):
                plan = f" Plan: `{case['plan'].get('chosen_plan')}`."
            add(f"- {SYSTEM_LABELS[name]} recall by ef (serial pass): {sweep}.{plan}")
        add("")

    if "milvus" not in systems:
        add("## Milvus")
        add("")
        add(comparison.get("milvus_missing_reason") or "Milvus was not run.")
        add("")

    add("## Notes")
    add("")
    for name in names:
        for note in systems[name].get("notes", []):
            add(f"- {SYSTEM_LABELS[name]}: {note}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--logpose", required=True, help="LogPose report")
    parser.add_argument("--milvus", help="Milvus report")
    parser.add_argument("--milvus-missing-reason", help="why Milvus was not run, for a LogPose-only summary")
    parser.add_argument("--resource", action="append", default=[], help="key=value recorded under resources")
    parser.add_argument("--json", required=True, help="combined JSON output")
    parser.add_argument("--md", required=True, help="Markdown output")
    args = parser.parse_args(argv)

    systems = {"logpose": load_report(args.logpose)}
    if args.milvus:
        systems["milvus"] = load_report(args.milvus)
    dataset = check_same_dataset(systems)
    targets = {report["target_recall"] for report in systems.values()}
    if len(targets) != 1:
        raise ValueError(f"reports use different target recalls: {sorted(targets)}")
    resources = {}
    for item in args.resource:
        key, _, value = item.partition("=")
        resources[key] = value
    comparison = {
        "schema": COMPARISON_SCHEMA,
        "generated_at": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M"),
        "generated_by": "scripts/bench-milvus.sh",
        "dataset": dataset,
        "machine": systems["logpose"]["machine"],
        "target_recall": targets.pop(),
        "resources": resources,
        "milvus_missing_reason": args.milvus_missing_reason,
        "systems": systems,
    }
    Path(args.json).parent.mkdir(parents=True, exist_ok=True)
    Path(args.json).write_text(json.dumps(comparison, indent=2) + "\n")
    Path(args.md).write_text(markdown(comparison))
    print(f"wrote {args.json} and {args.md}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
